name: kyverno-policy-test
on:
  - pull_request
  - workflow_dispatch
env:
  VERSION: v1.7.2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download Kyverno CLI
        run: |
          curl -sLO https://github.com/kyverno/kyverno/releases/download/${{ env.VERSION }}/kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          tar -xf kyverno-cli_${{ env.VERSION }}_linux_x86_64.tar.gz
          ./kyverno version 
      - name: Extraindo manifestos     
        run: |  
          helm template ./charts/helm-soma/ > manifesto.yaml
          mkdir resources
          mv manifesto.yaml ./resources
      - name: Test new resources against existing policies
        run: ./kyverno apply policies/ -r resources/
      - name: Test pre-defined cases
        run: ./kyverno test tests/
